;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	dired-unmark-backward
	evil-delete
	evil-exit-visual-state
	evil-insert
	evil-normal-state
	indent-for-tab-command
	kill-region
	org-self-insert-command
	paredit-doublequote
	paredit-forward-delete
	paredit-forward-slurp-sexp
	paredit-semicolon
	query-replace
	shell-command-on-region
	))

(setq mc/cmds-to-run-once
      '(
	dired-toggle-read-only
	end-of-buffer
	evil-append
	evil-delete-backward-char-and-join
	helm-M-x
	mouse-set-region
	))
